export const cardList = [
  {
    id: 1,
    topic: "Design",
    title: "Обсудить редизайн профиля",
    date: "18.09.2026",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Design",
    title: "Подобрать новые иконки для панели управления",
    date: "20.09.2026",
    status: "Без статуса",
  },
  {
    id: 3,
    topic: "Development",
    title: "Добавление темной темы оформления",
    date: "14.09.2026",
    status: "Нужно сделать",
  },
  {
    id: 4,
    topic: "Development",
    title: "Наполнение страницы 'О нас' текстами",
    date: "15.09.2026",
    status: "Нужно сделать",
  },
  {
    id: 5,
    topic: "Development",
    title: "Настройка мета-тегов для поисковиков",
    date: "16.09.2026",
    status: "Нужно сделать",
  },
  {
    id: 6,
    topic: "Development",
    title: "Интеграция API авторизации",
    date: "12.09.2026",
    status: "В работе",
  },
  {
    id: 7,
    topic: "Development",
    title: "Верстка адаптивного меню навигации",
    date: "12.09.2026",
    status: "В работе",
  },
  {
    id: 8,
    topic: "Testing",
    title: "Тестирование валидации форм регистрации",
    date: "13.09.2026",
    status: "Тестирование",
  },
  {
    id: 9,
    topic: "Testing",
    title: "Проверка кроссбраузерности на мобильных устройствах",
    date: "13.09.2026",
    status: "Тестирование",
  },
  {
    id: 10,
    topic: "Design",
    title: "Разработать макет главного экрана",
    date: "10.09.2026",
    status: "Готово",
  },
  {
    id: 11,
    topic: "Development",
    title: "Устранение багов",
    date: "11.09.2026",
    status: "Готово",
  },
  {
    id: 12,
    topic: "Testing",
    title: "Проверка соответствия макету",
    date: "13.09.2026",
    status: "Готово",
  },
];
